# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development: 
  adapter: postgresql 
  encoding: utf8 
  database: ca_site_dev 
  username: ca
  host: localhost
  pool: 5
  port: 5432
  password: 71 wilson street