# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35416cf85fe6e8469ce8bffb7353314654ebd0fe4780cc1bdbeb42a965543d32137112bbdf97571930e5fa57e310a04e08e85cc9a19247be5faf667c0fa4e392

test:
  secret_key_base: 7b368e3d94fad580d7a9f7022fc23ab5590dc07a2bc5d5d7af18f070c82d3358fc604c3db9ce95c987b3ddfc36019d5073d63de3d723d5f6a27ee61ac83d4028

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
